services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventario
    ports:
      - "5432:5432"

  backend:
    build: ./backend  # Asegúrate de que este directorio exista y tenga un Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/inventario
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend  # Asegúrate de que este directorio exista y tenga un Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend